### PR TITLE
Spanish

### PR DESCRIPTION
**Pull request by cristiandley**
Missing only 1 file to translate

`index.md`

If you accept the translation i will keep my work running :+1: just need to know if this is viable.

Thanks!

### CODE REVIEW

**Comment by cristiandley** [comment]
Should i bring spanish reviewers ? Thanks.

**Comment by helfer** [comment]
Wow, this is really cool, thanks @cristiandley! Before you look for reviewers, let me figure out how we could set up the docs to be in multiple languages. It might take a moment, but I'll get back to you once I know the answer.

**Comment by helfer** [comment]
@stubailo do we have translations of the Meteor docs? I think it would be cool to let folks translate the docs, but I'm not sure how to set it up. If it's a lot of work, it might not be worth it right now.

**Comment by p4bloch** [comment]
I would gladly help with the review/translate process :)

**Comment by cristiandley** [comment]
@helfer @stubailo  any news from this ?

what if we define a standar "topics" system ... and from that ground we start setting translations for each language. Eg.:

```
apollo-docs@0.9
- scalars
  - what is an scalar
  - something else
- migration
  - item
  - item
```

Docs use Hexo.io ? we could feed a base with this topic system.

(this is an idea, i would love to see translations... dont let die this)

**Comment by helfer** [comment]
@cristiandley I'd love to see translations, too, but unfortunately I have no idea to figure out how to make it work in Hexo. If you can figure it out (maybe starting here: https://hexo.io/docs/internationalization.html) I would definitely want to have a Spanish translation!

**Comment by cristiandley** [comment]
@helfer i have a bit of experience with Hexo.io ... i will try to do a Functional Demo of what i have in mind... give me a few days, dont close the PR.

**Comment by helfer** [comment]
One thing that is worth noting: Merging in a translation also means making a commitment to maintaining that translation. If it becomes outdated it will confuse people instead of helping them. Do you think you could maintain it or find other people to help you maintain it?

**Comment by cristiandley** [comment]
Of course i know the consecuences of doing this. Beyond that iv been involve in the meteor community since Meteor v0.6. Part of the solution i want to implement should know if the DOCS are or not outdated from the master branch.

We already have one possible contributor  ( @p4bloch ) who already helped on Discover Meteor translation. I think people join these causes with the right amount of publicity (Like the Discover Meteor Book did with just a Blog Post).

Thanks @helfer  :smile:

**Comment by theadactyl** [comment]
Closing this pull request as docs code has moved to the following repositories:
- [graphql-tools](https://github.com/apollographql/graphql-tools/tree/master/docs)
- [apollo-server](https://github.com/apollographql/apollo-server/tree/master/docs)
- [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/tree/master/docs)

Docs can be found live at apollographql.com here:
- [GraphQL Tools](https://www.apollographql.com/docs/graphql-tools/)
- [Apollo Server](https://www.apollographql.com/docs/apollo-server/)
- [Graphql Subscriptions](https://www.apollographql.com/docs/graphql-subscriptions/)

Thanks for your contribution - if you're still interested in providing Spanish translations of the new docs, I'd recommend popping into #contributing in [Apollo Slack](apollographql.com/#slack) so we can chat a bit about how this can be approached. 🙏

**Pull request closed without merging**
